#!/usr/bin/env python3

from argparse import ArgumentParser
from dotenv import find_dotenv, load_dotenv
from os import environ as env
from sys import argv

ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)

from pyrewall.utils.git_version import get_git_revision_short_hash

with open('VERSION', 'r') as version_file:
    v = version_file.read().strip()
    env['PYREWALL_VERSION'] = f'{v}+{get_git_revision_short_hash()}'


def main():
    
    parser = ArgumentParser()
    parser.add_argument('role', choices=['api', 'cli', 'priv', 'ctl'])
    args = parser.parse_args(argv[1:2])

    match args.role:
        case 'api':
            from pyrewall.api import app
            app.run(host='0.0.0.0', port=5050, debug=True)
        case 'cli':
            from pyrewall.cli import run_cli
            run_cli()
        case 'ctl':
            from pyrewall.control import main
            main(argv[2:])

if __name__ == '__main__':
    main()