"""Create UserGroup and add permission to group

Revision ID: 00e97aafa25f
Revises: 6421e55c2034
Create Date: 2024-09-30 02:35:43.569168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e97aafa25f'
down_revision: Union[str, None] = '6421e55c2034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_user_id'), 'user_groups', ['user_id'], unique=False)
    op.add_column('groups', sa.Column('permssions', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'permssions')
    op.drop_index(op.f('ix_user_groups_user_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
