"""add created/modified to user_groups table

Revision ID: bded222dc002
Revises: 85cf040c60db
Create Date: 2024-12-30 00:41:33.980816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bded222dc002'
down_revision: Union[str, None] = '85cf040c60db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('user_groups', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.add_column('user_groups', sa.Column('modified_date', sa.DateTime(), nullable=False))
    op.add_column('user_groups', sa.Column('modified_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_groups', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'user_groups', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_column('user_groups', 'modified_by')
    op.drop_column('user_groups', 'modified_date')
    op.drop_column('user_groups', 'created_by')
    op.drop_column('user_groups', 'created_date')
    # ### end Alembic commands ###
