"""add firewall tables

Revision ID: c7600a14ab79
Revises: f2c73101dace
Create Date: 2024-12-30 01:02:50.792567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7600a14ab79'
down_revision: Union[str, None] = 'f2c73101dace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('default_action', sa.Enum('Pass', 'Block', 'Reject', name='firewallaction'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_log', sa.Boolean(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firewall_tables_id'), 'firewall_tables', ['id'], unique=False)
    op.create_index(op.f('ix_firewall_tables_revision_id'), 'firewall_tables', ['revision_id'], unique=False)
    op.create_table('firewall_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firewall_table_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('Pass', 'Block', 'Reject', name='firewallaction'), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('ip_version', sa.Enum('Both', 'IPv4', 'IPv6', name='ipversion'), nullable=False),
    sa.Column('ip_protocol', sa.Enum(), nullable=False),
    sa.Column('invert_source_match', sa.Boolean(), nullable=False),
    sa.Column('source_address', postgresql.INET(), nullable=True),
    sa.Column('source_port_range', postgresql.INT4RANGE(), nullable=True),
    sa.Column('invert_destination_match', sa.Boolean(), nullable=False),
    sa.Column('destination_address', postgresql.INET(), nullable=True),
    sa.Column('destination_port_range', postgresql.INT4RANGE(), nullable=True),
    sa.Column('log', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['firewall_table_id'], ['firewall_tables.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firewall_rules_firewall_table_id'), 'firewall_rules', ['firewall_table_id'], unique=False)
    op.create_index(op.f('ix_firewall_rules_id'), 'firewall_rules', ['id'], unique=False)
    op.create_index(op.f('ix_firewall_rules_revision_id'), 'firewall_rules', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firewall_rules_revision_id'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules_id'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules_firewall_table_id'), table_name='firewall_rules')
    op.drop_table('firewall_rules')
    op.drop_index(op.f('ix_firewall_tables_revision_id'), table_name='firewall_tables')
    op.drop_index(op.f('ix_firewall_tables_id'), table_name='firewall_tables')
    op.drop_table('firewall_tables')
    # ### end Alembic commands ###
