"""add initial version of revisions table

Revision ID: f2c73101dace
Revises: bded222dc002
Create Date: 2024-12-30 01:00:00.881124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c73101dace'
down_revision: Union[str, None] = 'bded222dc002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('previous_revision_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('commit_date', sa.DateTime(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_id'), 'revisions', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_id'), table_name='revisions')
    op.drop_table('revisions')
    # ### end Alembic commands ###
