# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pyrewall.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pyrewall.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epyrewall.proto\x12\x08pyrewall\"\x0c\n\nvoidNoArgs\"&\n\x12SystemInfoResponse\x12\x10\n\x08hostname\x18\x01 \x01(\t2Q\n\nSystemInfo\x12\x43\n\rGetSystemInfo\x12\x14.pyrewall.voidNoArgs\x1a\x1c.pyrewall.SystemInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyrewall_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOIDNOARGS']._serialized_start=28
  _globals['_VOIDNOARGS']._serialized_end=40
  _globals['_SYSTEMINFORESPONSE']._serialized_start=42
  _globals['_SYSTEMINFORESPONSE']._serialized_end=80
  _globals['_SYSTEMINFO']._serialized_start=82
  _globals['_SYSTEMINFO']._serialized_end=163
# @@protoc_insertion_point(module_scope)
